//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Serv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serv.IServ")]
    public interface IServ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/LoginForm", ReplyAction="http://tempuri.org/IServ/LoginFormResponse")]
        string LoginForm(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/LoginForm", ReplyAction="http://tempuri.org/IServ/LoginFormResponse")]
        System.Threading.Tasks.Task<string> LoginFormAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/LoginForm_load", ReplyAction="http://tempuri.org/IServ/LoginForm_loadResponse")]
        char LoginForm_load(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/LoginForm_load", ReplyAction="http://tempuri.org/IServ/LoginForm_loadResponse")]
        System.Threading.Tasks.Task<char> LoginForm_loadAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Fac_find_stud", ReplyAction="http://tempuri.org/IServ/Fac_find_studResponse")]
        string Fac_find_stud(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Fac_find_stud", ReplyAction="http://tempuri.org/IServ/Fac_find_studResponse")]
        System.Threading.Tasks.Task<string> Fac_find_studAsync(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Spec_find_stud", ReplyAction="http://tempuri.org/IServ/Spec_find_studResponse")]
        string Spec_find_stud(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Spec_find_stud", ReplyAction="http://tempuri.org/IServ/Spec_find_studResponse")]
        System.Threading.Tasks.Task<string> Spec_find_studAsync(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Sal_find_stud", ReplyAction="http://tempuri.org/IServ/Sal_find_studResponse")]
        string Sal_find_stud(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Sal_find_stud", ReplyAction="http://tempuri.org/IServ/Sal_find_studResponse")]
        System.Threading.Tasks.Task<string> Sal_find_studAsync(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Take_table", ReplyAction="http://tempuri.org/IServ/Take_tableResponse")]
        System.Data.DataTable Take_table(string table, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Take_table", ReplyAction="http://tempuri.org/IServ/Take_tableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Take_tableAsync(string table, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Take_rows", ReplyAction="http://tempuri.org/IServ/Take_rowsResponse")]
        System.Data.DataTable Take_rows(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Take_rows", ReplyAction="http://tempuri.org/IServ/Take_rowsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Take_rowsAsync(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Update_table", ReplyAction="http://tempuri.org/IServ/Update_tableResponse")]
        string Update_table(string table, string name_set, string set, string where, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Update_table", ReplyAction="http://tempuri.org/IServ/Update_tableResponse")]
        System.Threading.Tasks.Task<string> Update_tableAsync(string table, string name_set, string set, string where, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Delete_table", ReplyAction="http://tempuri.org/IServ/Delete_tableResponse")]
        string Delete_table(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Delete_table", ReplyAction="http://tempuri.org/IServ/Delete_tableResponse")]
        System.Threading.Tasks.Task<string> Delete_tableAsync(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Top_Sal", ReplyAction="http://tempuri.org/IServ/Top_SalResponse")]
        string Top_Sal(string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Top_Sal", ReplyAction="http://tempuri.org/IServ/Top_SalResponse")]
        System.Threading.Tasks.Task<string> Top_SalAsync(string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Exit_to_del", ReplyAction="http://tempuri.org/IServ/Exit_to_delResponse")]
        string Exit_to_del(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Exit_to_del", ReplyAction="http://tempuri.org/IServ/Exit_to_delResponse")]
        System.Threading.Tasks.Task<string> Exit_to_delAsync(string id, string select_online);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Insert_Online", ReplyAction="http://tempuri.org/IServ/Insert_OnlineResponse")]
        void Insert_Online(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Insert_Online", ReplyAction="http://tempuri.org/IServ/Insert_OnlineResponse")]
        System.Threading.Tasks.Task Insert_OnlineAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Delete_Online", ReplyAction="http://tempuri.org/IServ/Delete_OnlineResponse")]
        void Delete_Online(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServ/Delete_Online", ReplyAction="http://tempuri.org/IServ/Delete_OnlineResponse")]
        System.Threading.Tasks.Task Delete_OnlineAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServChannel : Client.Serv.IServ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServClient : System.ServiceModel.ClientBase<Client.Serv.IServ>, Client.Serv.IServ {
        
        public ServClient() {
        }
        
        public ServClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginForm(string login, string password) {
            return base.Channel.LoginForm(login, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginFormAsync(string login, string password) {
            return base.Channel.LoginFormAsync(login, password);
        }
        
        public char LoginForm_load(string id) {
            return base.Channel.LoginForm_load(id);
        }
        
        public System.Threading.Tasks.Task<char> LoginForm_loadAsync(string id) {
            return base.Channel.LoginForm_loadAsync(id);
        }
        
        public string Fac_find_stud(string id, string select_online) {
            return base.Channel.Fac_find_stud(id, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Fac_find_studAsync(string id, string select_online) {
            return base.Channel.Fac_find_studAsync(id, select_online);
        }
        
        public string Spec_find_stud(string id, string select_online) {
            return base.Channel.Spec_find_stud(id, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Spec_find_studAsync(string id, string select_online) {
            return base.Channel.Spec_find_studAsync(id, select_online);
        }
        
        public string Sal_find_stud(string id, string select_online) {
            return base.Channel.Sal_find_stud(id, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Sal_find_studAsync(string id, string select_online) {
            return base.Channel.Sal_find_studAsync(id, select_online);
        }
        
        public System.Data.DataTable Take_table(string table, string select_online) {
            return base.Channel.Take_table(table, select_online);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Take_tableAsync(string table, string select_online) {
            return base.Channel.Take_tableAsync(table, select_online);
        }
        
        public System.Data.DataTable Take_rows(string table) {
            return base.Channel.Take_rows(table);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Take_rowsAsync(string table) {
            return base.Channel.Take_rowsAsync(table);
        }
        
        public string Update_table(string table, string name_set, string set, string where, string select_online) {
            return base.Channel.Update_table(table, name_set, set, where, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Update_tableAsync(string table, string name_set, string set, string where, string select_online) {
            return base.Channel.Update_tableAsync(table, name_set, set, where, select_online);
        }
        
        public string Delete_table(string id, string select_online) {
            return base.Channel.Delete_table(id, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Delete_tableAsync(string id, string select_online) {
            return base.Channel.Delete_tableAsync(id, select_online);
        }
        
        public string Top_Sal(string select_online) {
            return base.Channel.Top_Sal(select_online);
        }
        
        public System.Threading.Tasks.Task<string> Top_SalAsync(string select_online) {
            return base.Channel.Top_SalAsync(select_online);
        }
        
        public string Exit_to_del(string id, string select_online) {
            return base.Channel.Exit_to_del(id, select_online);
        }
        
        public System.Threading.Tasks.Task<string> Exit_to_delAsync(string id, string select_online) {
            return base.Channel.Exit_to_delAsync(id, select_online);
        }
        
        public void Insert_Online(string id) {
            base.Channel.Insert_Online(id);
        }
        
        public System.Threading.Tasks.Task Insert_OnlineAsync(string id) {
            return base.Channel.Insert_OnlineAsync(id);
        }
        
        public void Delete_Online(string id) {
            base.Channel.Delete_Online(id);
        }
        
        public System.Threading.Tasks.Task Delete_OnlineAsync(string id) {
            return base.Channel.Delete_OnlineAsync(id);
        }
    }
}
